version: '3'
services:
  jiushi-live-user-provider-docker-1:
    container_name: jiushi-live-user-provider-docker-1
    image: '192.168.1.20/jiushi-live/jiushi-live-user-provider-docker:1.0.0'
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 256m
    ports:
      - "9091:9091"
      - "12000:12000"
    volumes:
      - /tmp/logs/jiushi-live-user-provider:/tmp/logs/jiushi-live-user-provider
    environment:
      - TZ=Asia/Shanghai
      - DUBBO_IP_TO_REGISTRY=192.168.1.20
      - DUBBO_PORT_TO_REGISTRY=9091
      - DUBBO_PORT_TO_BIND=9091
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx128m -Xmn128m -Xss256k


  jiushi-live-user-provider-docker-2:
    container_name: jiushi-live-user-provider-docker-2
    image: '192.168.1.20/jiushi-live/jiushi-live-user-provider-docker:1.0.0'
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 256m
    ports:
      - "9092:9092"
      - "12001:12000"
    volumes:
      - /tmp/logs/jiushi-live-user-provider:/tmp/logs/jiushi-live-user-provider
    environment:
      - TZ=Asia/Shanghai
      - DUBBO_IP_TO_REGISTRY=192.168.1.20
      - DUBBO_PORT_TO_REGISTRY=9092
      - DUBBO_PORT_TO_BIND=9092
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx128m -Xmn128m -Xss256k
