version: '3'
services:
  jiushi-live-im-core-servers-1:
    container_name: jiushi-live-im-core-server-1
    image: '192.168.1.20/jiushi-live/jiushi-live-im-core-server-docker:1.0.0'
    ports:
      - "18085:18085"
      - "18086:18086"
    volumes:
      - /tmp/logs/jiushi-live-im-core-server:/tmp/logs/jiushi-live-im-core-server
    environment:
      - TZ=Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 256m
  jiushi-live-im-core-servers-2:
    container_name: jiushi-live-im-core-server-2
    image: '192.168.1.20/jiushi-live/jiushi-live-im-core-server-docker:1.0.0'
    ports:
#可以容器内部接口不变，宿主机映射端口变了就行
      - "18095:18085"
      - "18096:18086"
    volumes:
      - /tmp/logs/jiushi-live-im-core-server:/tmp/logs/jiushi-live-im-core-server
    environment:
      - TZ=Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 256m