spring:
  application:
    name: jiushi-live-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:nacos:192.168.1.20:8848:jiushi-live-user-shardingjdbc.yaml?username=nacos&&password=nacos&&namespace=jiushiLive
    hikari:
      pool-name: jiushi-user-pool
      minimum-idle: 100
      maximum-pool-size: 300
      idle-timeout: 60000
      connection-timeout: 4000
      max-lifetime: 60000
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    #docker启动的时候，注入host的配置
    address: nacos://192.168.1.20:8848?namespace=jiushiLive&&username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: 9091
    threadpool: fixed
    dispatcher: execution
    threads: 500
    accepts: 500
    qos-port: 22223
  consumer:
    timeout: 50000
    loadbalance: roundrobin
    check: false
jiushi:
  rmq:
    consumer:
      nameSrv: 192.168.1.20:9876
      groupName: ${spring.application.name}ConsumerGroup
      consumeTimeout: 10000
    producer:
      nameSrv: 192.168.1.20:9876
      groupName: ${spring.application.name}ProducerGroup
      applicationName: ${spring.application.name}ProducerApplic
      sendMsgTimeout: 3000
      retryTimes: 3