spring:
  application:
    name: jiushi-live-im-core-server
  cloud:
    nacos:
      discovery:
        ip: mylove7.top
  data:
    redis:
      port: 6379
      host: mylove7.top
      password: mylovezq
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10
jiushi:
  im:
    tcp:
      port: 18085
    ws:
      port: 18086

  rmq:
    producer:
      nameSrv: mylove7.top:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://mylove7.top:8848?namespace=jiushiLive&&username=nacos&&password=nacos
  protocol:
    port: 9100