spring:
  application:
    name: jiushi-live-account-provider
  data:
    redis:
      port: 6379
      host: mylove7.top
      password: mylovezq
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    #docker启动的时候，注入host的配置
    address: nacos://mylove7.top:8848?namespace=jiushiLive&&username=nacos&&password=nacos
  protocol:
    name: spring
    port: 9096
    threadpool: fixed
    dispatcher: execution
    threads: 500
    accepts: 500