spring:
  application:
    name: jiushi-live-bank-provider
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
    driver-class-name: com.mysql.cj.jdbc.Driver
    #访问主库
    url: jdbc:mysql://192.168.1.20:3306/qiyu_live_bank?useUnicode=true&characterEncoding=utf8
    username: root
    password: mylovezq

  data:
    redis:
      port: 6379
      host: 192.168.1.20
      password: mylovezq
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    #docker启动的时候，注入host的配置
    address: nacos://192.168.1.20:8848?namespace=jiushiLive&&username=qiyu&&password=qiyu
  protocol:
    name: dubbo
    port: 9096
    threadpool: fixed
    dispatcher: execution
    threads: 500
    accepts: 500

qiyu:
  rmq:
    producer:
      nameSrv: 192.168.1.20:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2