spring:
  application:
    name: jiushi-live-id-generate-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #访问主库
    url: jdbc:mysql://mylove7.top:3306/jiushi_live_common?useUnicode=true&characterEncoding=utf8
    username: root
    password: mylovezq

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://mylove7.top:8848?namespace=jiushiLive&&username=jiushi&&password=jiushi
  protocol:
    name: spring
    port: 9092