spring:
  application:
    name: jiushi-live-im-router-provider
  data:
    redis:
      port: 6379
      host: mylove7.top
      password: mylovezq
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10
jiushi:
  rmq:
    producer:
      nameSrv: mylove7.top:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://mylove7.top:8848?namespace=jiushiLive&&username=jiushi&&password=jiushi
  protocol:
    port: 9098
