spring:
  application:
    name: jiushi-live-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:nacos:mylove7.top:8848:jiushi-live-user-shardingjdbc.yaml?username=nacos&&password=nacos&&namespace=jiushiLive
    hikari:
      pool-name: jiushi-user-pool
      minimum-idle: 100
      maximum-pool-size: 300
      idle-timeout: 60000
      connection-timeout: 4000
      max-lifetime: 60000
  data:
    redis:
      port: 6379
      host: mylove7.top
      password: mylovezq
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10
jiushi:
  rmq:
    consumer:
      nameSrv: mylove7.top:9876
      groupName: jiushiLiveMqApplication
    producer:
      nameSrv: mylove7.top:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2


dubbo:
  application:
    name: ${spring.application.name}
  registry:
    #docker启动的时候，注入host的配置
    address: nacos://mylove7.top:8848?namespace=jiushiLive&&username=nacos&&password=nacos
  protocol:
    name: spring
    port: 9090
    threadpool: fixed
    dispatcher: execution
    threads: 500
    accepts: 500
