spring:
  application:
    name: jiushi-live-bank-api
dubbo:
  application:
    name: jiushi-live-bank-api
    qos-enable: false
  registry:
    address: nacos://192.168.1.20:8848?namespace=jiushiLive&&username=qiyu&&password=qiyu

server:
  port: 8201
  servlet:
    context-path: /live/bank