spring:
  application:
    name: jiushi-live-msg-provider
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
    driver-class-name: com.mysql.cj.jdbc.Driver
    #访问主库
    url: jdbc:mysql://cloud.msg.db:8808/jiushi_live_msg?useUnicode=true&characterEncoding=utf8
    username: root
    password: mylovezq
  data:
    redis:
      port: 6379
      host: 192.168.1.20
      password: mylovezq
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10

jiushi:
  sms:
    ccp:
      smsServerIp: app.cloopen.com
      port: 8883
      accountSId: [容联云上的accountSID]
      accountToken: [容联云上的Token]
      appId: [容联云上的appId]
      templateId: 1
      testPhone: 13510647925

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://192.168.1.20:8848?namespace=jiushiLive&&username=jiushi&&password=jiushi
  protocol:
    name: dubbo
    port: 9090