spring:
  application:
    name: jiushi-live-gift-provider
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
    driver-class-name: com.mysql.cj.jdbc.Driver
    #访问主库
    url: jdbc:mysql://mylove7.top:3306/jiushi_live_gift?useUnicode=true&characterEncoding=utf8
    username: root
    password: mylovezq
  data:
    redis:
      port: 6379
      host: mylove7.top
      password: mylovezq
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10

jiushi:
  rmq:
    consumer:
      nameSrv: mylove7.top:9876
      groupName: jiushiLiveMqApplication
    producer:
      nameSrv: mylove7.top:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://mylove7.top:8848?namespace=jiushiLive&&username=jiushi&&password=jiushi
  protocol:
    name: spring
    port: 9093