version: '3'
services:
  jiushi-gateway-provider-1:
    container_name: jiushi-live-gateway-1
    image: '192.168.1.20/jiushi-live/jiushi-live-gateway-docker:1.0.0'
    ports:
      - "80:80"
    volumes:
      - /tmp/logs/jiushi-live-live-gateway:/tmp/logs/jiushi-live-live-gateway
    environment:
      - TZ=Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 128m