version: '3'
services:
  jiushi-live-gift-provider-1:
    container_name: jiushi-live-gift-provider-1
    image: 'mylove7.top/jiushi-live/jiushi-live-gift-provider-docker:1.0.0'
    ports:
      - "9098:9090"
    volumes:
      - /tmp/logs/jiushi-live-gift-provider:/tmp/logs/jiushi-live-gift-provider
    environment:
      - DUBBO_IP_TO_REGISTRY=106.55.106.248
      - DUBBO_PORT_TO_REGISTRY=9098
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-DNACOS_USER=nacos_rw -DNACOS_PWD=nacos1867122 -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k
    extra_hosts:
      - '192.168.1.20:175.178.130.183'
      - 'cloud.db:175.178.130.183'
      - '192.168.1.20:119.29.239.77'